#include "Protocolo.h"

int main()
{
    srand(time(NULL));
    cout << "Protocolo!" << endl;
    Protocolo p("243","PMC","MAR","CH");
    string mensaje = "TEESTOYBUSCANDOPARAEXPLOTARCONTIGOPARAEXPLOTARCONTIGOPARAEXPLOTARNOSTEESTOYLLAMANDOPARAVOLARCONTIGOZTEESTOYBUSCANDOPARAEXPLOTARCONTIGOPARAEXPLOTARCONTIGOPARAEXPLOTARNOSTEESTOYLLAMANDOPARAVOLARCONTIGOZTEESTOYBUSCANDOPARAEXPLOTARCONTIGOPARAEXPLOTARCONTIGOPARAEXPLOTARNOSTEESTOYLLAMANDOPARAVOLARCONTIGOZTEESTOYBUSCANDOPARAEXPLOTARCONTIGOPARAEXPLOTARCONTIGOPARAEXPLOTARNOSTEESTOYLLAMANDOPARAVOLARCONTIGOZTEESTOYBUSCANDOPARAEXPLOTARCONTIGOPARAEXPLOTARCONTIGOPARAEXPLOTARNOSTEESTOYLLAMANDOPARAVOLARCONTIGOZ";
    string encriptado = p.Encriptado(mensaje);
    ///cout <<"ENCRIPTAO: "<<encriptado<<endl;
    string desencriptado = p.Desencriptado();
    cout <<"DESENCRIPTAO: "<<desencriptado<<endl;
    /*culo.leer_txt();
    culo.escribir_txt("TE ESTOY LLAMANDO PARA EXPLOTAR CONTIGO");
    culo.leer_txt();*/
    /*Enigma e("ABC",1,2,3,"RFW","GH");
    string wea = e.Desencriptado("RXATTSFKVJANRFYNUEIFNOBFYSPVAQACJSF");
    cout <<wea<<endl;*/




    return 0;
}
